//export const DATABASE_CONNECTION_TOKEN = 'DATABASE_CONNECTION_TOKEN';
//export const MYSQL_CONNECTION_TOKEN = 'MYSQL_CONNECTION_TOKEN';
//export const SQLITE_CONNECTION_TOKEN = 'SQLITE_CONNECTION_TOKEN'; // for testing
